package fr.olaqin.pfd.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import fr.olaqin.pfd.enums.Civilite;
import fr.olaqin.pfd.enums.RaisonQualif;
import fr.olaqin.pfd.enums.ResultatQualif;
import fr.olaqin.pfd.enums.TypeProfession;
import fr.olaqin.pfd.enums.converter.CiviliteConverter;
import fr.olaqin.pfd.enums.converter.RaisonQualifConverter;
import fr.olaqin.pfd.enums.converter.ResultatQualifConverter;
import fr.olaqin.pfd.enums.converter.TypeProfessionConverter;
import lombok.*;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@EqualsAndHashCode(callSuper = false)
@DynamoDBTable(tableName = "ProfessionnelSanteProspect")
public class    ProfessionnelSanteProspect extends CommonEntity {

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBTypeConverted(converter = CiviliteConverter.class)
    @DynamoDBAttribute(attributeName = "Civilite")
    private Civilite civilite;
    @DynamoDBAttribute(attributeName = "Nom")
    private String nom;
    @DynamoDBAttribute(attributeName = "Prenom")
    private String prenom;
    @DynamoDBAttribute(attributeName = "Email")
    private String email;
    @DynamoDBAttribute(attributeName = "Telephone")
    private String telephone;
    @DynamoDBAttribute(attributeName = "CodePostal")
    private String codePostal;
    @DynamoDBTypeConverted(converter = TypeProfessionConverter.class)
    @DynamoDBAttribute(attributeName = "Profession")
    private TypeProfession profession;
    @DynamoDBAttribute(attributeName = "ReponseAutreProfession")
    private String reponseAutreProfession;
    @DynamoDBAttribute(attributeName = "AccepteEtreRecontacte")
    private Boolean accepteEtreRecontacte;

    @DynamoDBTypeConverted(converter = ResultatQualifConverter.class)
    @DynamoDBAttribute(attributeName = "ResultatQualif")
    private ResultatQualif resultatQualif;
    @DynamoDBTypeConverted(converter = RaisonQualifConverter.class)
    @DynamoDBAttribute(attributeName = "RaisonQualif")
    private RaisonQualif raisonQualif;

}
