amazon:
  aws:
    accesskey: keyId
    secretkey: secretKey
    region: eu-west-3
  dynamodb:
    endpoint: http://localhost:8000/
application:
  asip:
    cron: 0 44 18 * * *
    url: http://localhost:8080/api/annuaire/asipFile
    size:
