const BASE_URL = 'localhost:8080';

const API_VERSION = '1.0';

const PROSPECTS_PATH = `/api/${API_VERSION}/prospects`;
const UTILISATEURS_PATH = `/api/${API_VERSION}/utilisateurs`;
const ANNUAIRE_PROFESSIONNELS_PATH = `/api/${API_VERSION}/professionnels-sante-en-activite/annuaire`;

const API_PROSPECTS = `${BASE_URL}${PROSPECTS_PATH}`;
const API_UTILISATEURS = `${BASE_URL}${UTILISATEURS_PATH}`;
const API_ANNUAIRE_PROFESSIONNELS = `${BASE_URL}${ANNUAIRE_PROFESSIONNELS_PATH}`;

export {
  BASE_URL,
  API_PROSPECTS,
  API_UTILISATEURS,
  API_ANNUAIRE_PROFESSIONNELS,
  PROSPECTS_PATH,
  UTILISATEURS_PATH,
  ANNUAIRE_PROFESSIONNELS_PATH
};
