package fr.olaqin.pfdbatch.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import static org.apache.commons.lang3.StringUtils.replaceEach;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@DynamoDBTable(tableName = "AnnuaireProfessionnelSanteEnActivite")
public class AnnuaireProfessionnelSanteEnActivite {

    public static final String ENTITY_NAME = "AnnuaireProfessionnelSanteEnActivite";
    public static final String NOM_PRENOM_CODE_POSTAL_INDEX = "NomPrenomCodePostalIndex";

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "TypeIdentifiantPP")
    private String typeIdentifiantPP;
    @DynamoDBAttribute(attributeName = "IdentifiantPP")
    private String identifiantPP;
    @DynamoDBAttribute(attributeName = "IdentificationNationalePP")
    private String identificationNationalePP;
    @DynamoDBAttribute(attributeName = "CodeCiviliteExercice")
    private String codeCiviliteExercice;
    @DynamoDBAttribute(attributeName = "LibelleCiviliteExercice")
    private String libelleCiviliteExercice;
    @DynamoDBAttribute(attributeName = "CodeCivilite")
    private String codeCivilite;
    @DynamoDBAttribute(attributeName = "LibelleCivilite")
    private String libelleCivilite;
    @DynamoDBAttribute(attributeName = "NomExercice")
    private String nomExercice;
    @DynamoDBAttribute(attributeName = "PrenomExercice")
    private String prenomExercice;
    @DynamoDBAttribute(attributeName = "CodeProfession")
    private String codeProfession;
    @DynamoDBAttribute(attributeName = "LibelleProfession")
    private String libelleProfession;
    @DynamoDBAttribute(attributeName = "CodeCategorieProfessionnelle")
    private String codeCategorieProfessionnelle;
    @DynamoDBAttribute(attributeName = "LibelleCategorieProfessionnelle")
    private String libelleCategorieProfessionnelle;
    @DynamoDBAttribute(attributeName = "CodeTypeSavoirFaire")
    private String codeTypeSavoirFaire;
    @DynamoDBAttribute(attributeName = "LibelleTypeSavoirFaire")
    private String libelleTypeSavoirFaire;
    @DynamoDBAttribute(attributeName = "CodeSavoirFaire")
    private String codeSavoirFaire;
    @DynamoDBAttribute(attributeName = "LibelleSavoirFaire")
    private String libelleSavoirFaire;
    @DynamoDBAttribute(attributeName = "CodeModeExercice")
    private String codeModeExercice;
    @DynamoDBAttribute(attributeName = "LibelleModeExercice")
    private String libelleModeExercice;
    @DynamoDBAttribute(attributeName = "NumeroSiretSite")
    private String numeroSiretSite;
    @DynamoDBAttribute(attributeName = "NumeroSirenSite")
    private String numeroSirenSite;
    @DynamoDBAttribute(attributeName = "NumeroFinessSite")
    private String numeroFinessSite;
    @DynamoDBAttribute(attributeName = "NumeroFinessEtablissementJuridique")
    private String numeroFinessEtablissementJuridique;
    @DynamoDBAttribute(attributeName = "IdentifiantTechniqueStructure")
    private String identifiantTechniqueStructure;
    @DynamoDBAttribute(attributeName = "RaisonSocialeSite")
    private String raisonSocialeSite;
    @DynamoDBAttribute(attributeName = "EnseigneCommercialeSite")
    private String enseigneCommercialeSite;
    @DynamoDBAttribute(attributeName = "ComplementDestinataireCoordStructure")
    private String complementDestinataireCoordStructure;
    @DynamoDBAttribute(attributeName = "ComplementGeographiqueCoordStructure")
    private String complementGeographiqueCoordStructure;
    @DynamoDBAttribute(attributeName = "NumeroVoieCoordStructure")
    private String numeroVoieCoordStructure;
    @DynamoDBAttribute(attributeName = "IndiceRepetitionCoordStructure")
    private String indiceRepetitionCoordStructure;
    @DynamoDBAttribute(attributeName = "CodeTypeVoieCoordStructure")
    private String codeTypeVoieCoordStructure;
    @DynamoDBAttribute(attributeName = "LibelleTypeVoieCoordStructure")
    private String libelleTypeVoieCoordStructure;
    @DynamoDBAttribute(attributeName = "LibelleVoieCoordStructure")
    private String libelleVoieCoordStructure;
    @DynamoDBAttribute(attributeName = "MentionDistributionCoordStructure")
    private String mentionDistributionCoordStructure;
    @DynamoDBAttribute(attributeName = "BureauCedexCoordStructure")
    private String bureauCedexCoordStructure;
    @DynamoDBAttribute(attributeName = "CodePostalCoordStructure")
    private String codePostalCoordStructure;
    @DynamoDBAttribute(attributeName = "CodeCommuneCoordStructure")
    private String codeCommuneCoordStructure;
    @DynamoDBAttribute(attributeName = "LibelleCommuneCoordStructure")
    private String libelleCommuneCoordStructure;
    @DynamoDBAttribute(attributeName = "CodePaysCoordStructure")
    private String codePaysCoordStructure;
    @DynamoDBAttribute(attributeName = "LibellePaysCoordStructure")
    private String libellePaysCoordStructure;
    @DynamoDBAttribute(attributeName = "TelephoneCoordStructure")
    private String telephoneCoordStructure;
    @DynamoDBAttribute(attributeName = "Telephone2CoordStructure")
    private String telephone2CoordStructure;
    @DynamoDBAttribute(attributeName = "TelecopieCoordStructure")
    private String telecopieCoordStructure;
    @DynamoDBAttribute(attributeName = "AdresseEmailCoordStructure")
    private String adresseEmailCoordStructure;
    @DynamoDBAttribute(attributeName = "CodeDepartementStructure")
    private String codeDepartementStructure;
    @DynamoDBAttribute(attributeName = "LibelleDepartementStructure")
    private String libelleDepartementStructure;
    @DynamoDBAttribute(attributeName = "AncienIdentifiantStructure")
    private String ancienIdentifiantStructure;
    @DynamoDBAttribute(attributeName = "AutoriteEnregistrement")
    private String autoriteEnregistrement;
    @DynamoDBAttribute(attributeName = "CodeSecteurActivite")
    private String codeSecteurActivite;
    @DynamoDBAttribute(attributeName = "LibelleSecteurActivite")
    private String libelleSecteurActivite;
    @DynamoDBAttribute(attributeName = "CodeSectionTableauPharmaciens")
    private String codeSectionTableauPharmaciens;
    @DynamoDBAttribute(attributeName = "LibelleSectionTableauPharmaciens")
    private String libelleSectionTableauPharmaciens;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = NOM_PRENOM_CODE_POSTAL_INDEX)
    @DynamoDBAttribute(attributeName = "NomExerciceSearch")
    private String nomExerciceSearch;
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = NOM_PRENOM_CODE_POSTAL_INDEX)
    @DynamoDBAttribute(attributeName = "PrenomExerciceSearch")
    private String prenomExerciceSearch;

    public void setNomExercice(String nomExercice) {
        this.nomExercice = nomExercice;
        setNomExerciceSearch(replaceAccent(nomExercice.toLowerCase()));
    }

    public void setPrenomExercice(String prenomExercice) {
        this.prenomExercice = prenomExercice;
        setPrenomExerciceSearch(replaceAccent(prenomExercice.toLowerCase()));
    }

    private String replaceAccent(String word) {
        final String accents = "ÀÁÂÃÄÅàáâãäåÈÉÊËèéêëç";
        final String letters = "AAAAAAaaaaaaEEEEeeeec";

        return replaceEach(word, accents.split(""), letters.split(""));
    }
}